// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project.Context;

#nullable disable

namespace Project.Migrations
{
    [DbContext(typeof(ApbdProjectContext))]
    [Migration("20240628215625_mockDataAdded")]
    partial class mockDataAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DiscountSoftwareSystem", b =>
                {
                    b.Property<int>("DiscountsIdDiscount")
                        .HasColumnType("int");

                    b.Property<int>("SoftwareSystemsId")
                        .HasColumnType("int");

                    b.HasKey("DiscountsIdDiscount", "SoftwareSystemsId");

                    b.HasIndex("SoftwareSystemsId");

                    b.ToTable("DiscountSoftwareSystem");
                });

            modelBuilder.Entity("Project.Models.AppUser", b =>
                {
                    b.Property<string>("Login")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Roles")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Login");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Login = "Employee",
                            Password = "12345",
                            Roles = "Employee"
                        },
                        new
                        {
                            Login = "Admin",
                            Password = "qwerty",
                            Roles = "Admin,Employee"
                        });
                });

            modelBuilder.Entity("Project.Models.Client", b =>
                {
                    b.Property<int>("IdClient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdClient"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("IdClient");

                    b.ToTable("Clients");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Client");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Project.Models.Contract", b =>
                {
                    b.Property<int>("IdContract")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdContract"));

                    b.Property<int>("DurationInYears")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdClient")
                        .HasColumnType("int");

                    b.Property<int>("IdSoftwareSystem")
                        .HasColumnType("int");

                    b.Property<double>("Paid")
                        .HasColumnType("float");

                    b.Property<bool>("PreviousClientDiscount")
                        .HasColumnType("bit");

                    b.Property<double>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("float(10)");

                    b.Property<string>("SoftwareSystemVersion")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Updates")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("IdContract");

                    b.HasIndex("IdClient");

                    b.HasIndex("IdSoftwareSystem");

                    b.ToTable("Contracts");

                    b.HasData(
                        new
                        {
                            IdContract = 1,
                            DurationInYears = 1,
                            EndDate = new DateTime(2024, 7, 8, 23, 56, 24, 397, DateTimeKind.Local).AddTicks(5830),
                            IdClient = 1,
                            IdSoftwareSystem = 1,
                            Paid = 0.0,
                            PreviousClientDiscount = true,
                            Price = 100.0,
                            SoftwareSystemVersion = "1.0",
                            StartDate = new DateTime(2024, 6, 28, 23, 56, 24, 397, DateTimeKind.Local).AddTicks(5490),
                            Updates = "TestUpdates"
                        },
                        new
                        {
                            IdContract = 2,
                            DurationInYears = 1,
                            EndDate = new DateTime(2024, 7, 8, 23, 56, 24, 397, DateTimeKind.Local).AddTicks(5850),
                            IdClient = 2,
                            IdSoftwareSystem = 2,
                            Paid = 0.0,
                            PreviousClientDiscount = false,
                            Price = 200.0,
                            SoftwareSystemVersion = "2.0",
                            StartDate = new DateTime(2024, 6, 28, 23, 56, 24, 397, DateTimeKind.Local).AddTicks(5850),
                            Updates = "TestUpdates2"
                        });
                });

            modelBuilder.Entity("Project.Models.Discount", b =>
                {
                    b.Property<int>("IdDiscount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDiscount"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("ForSubscription")
                        .HasColumnType("bit");

                    b.Property<bool>("ForUpfront")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Percentage")
                        .HasColumnType("float");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("IdDiscount");

                    b.ToTable("Discounts");
                });

            modelBuilder.Entity("Project.Models.SoftwareSystem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<double>("YearlyPrice")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("SoftwareSystems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "TestCategory",
                            Description = "TestDescription",
                            Name = "TestName",
                            Version = "1.0",
                            YearlyPrice = 100.0
                        },
                        new
                        {
                            Id = 2,
                            Category = "TestCategory2",
                            Description = "TestDescription2",
                            Name = "TestName2",
                            Version = "2.0",
                            YearlyPrice = 200.0
                        });
                });

            modelBuilder.Entity("Project.Models.CompanyClient", b =>
                {
                    b.HasBaseType("Project.Models.Client");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("KrsNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasDiscriminator().HasValue("CompanyClient");

                    b.HasData(
                        new
                        {
                            IdClient = 2,
                            Address = "TestAddress",
                            Email = "test@gmail.com",
                            PhoneNumber = "123456789",
                            CompanyName = "TestCompanyName",
                            KrsNumber = "1234567890"
                        });
                });

            modelBuilder.Entity("Project.Models.IndividualClient", b =>
                {
                    b.HasBaseType("Project.Models.Client");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Pesel")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.HasDiscriminator().HasValue("IndividualClient");

                    b.HasData(
                        new
                        {
                            IdClient = 1,
                            Address = "TestAddress",
                            Email = "test@gmail.com",
                            PhoneNumber = "123456789",
                            FirstName = "TestFirstName",
                            IsDeleted = false,
                            LastName = "TestLastName",
                            Pesel = "12345678901"
                        });
                });

            modelBuilder.Entity("DiscountSoftwareSystem", b =>
                {
                    b.HasOne("Project.Models.Discount", null)
                        .WithMany()
                        .HasForeignKey("DiscountsIdDiscount")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.Models.SoftwareSystem", null)
                        .WithMany()
                        .HasForeignKey("SoftwareSystemsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Project.Models.Contract", b =>
                {
                    b.HasOne("Project.Models.Client", "Client")
                        .WithMany("Contracts")
                        .HasForeignKey("IdClient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.Models.SoftwareSystem", "SoftwareSystem")
                        .WithMany("Contracts")
                        .HasForeignKey("IdSoftwareSystem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("SoftwareSystem");
                });

            modelBuilder.Entity("Project.Models.Client", b =>
                {
                    b.Navigation("Contracts");
                });

            modelBuilder.Entity("Project.Models.SoftwareSystem", b =>
                {
                    b.Navigation("Contracts");
                });
#pragma warning restore 612, 618
        }
    }
}
